// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgwveewvvcbiycokouhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpnd3ZlZXd2dmNiaXljb2tvdWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNjA2NTksImV4cCI6MjA1NjgzNjY1OX0.aMjZ5x0gBkQfEgCMSalIqCpdT9SVjwkb1OP_kh2VyeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);